name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v6
      - name: "Update dependencies"
        run: sudo apt-get update
      - name: "Install dependencies"
        run: sudo apt-get install -y build-essential cmake pkg-config qtbase5-dev libqt5opengl5-dev libgl1-mesa-dev libglu1-mesa-dev libprotobuf-dev protobuf-compiler libode-dev libboost-dev
      - name: "Build"
        run: make

  build-macos:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
    steps:
      - uses: actions/checkout@v6
      - name: "Install dependencies"
        run: brew tap robotology/formulae && brew install cmake pkg-config qt@5 ode
      - name: "Build"
        run: |
          # For macOS 14+  (Apple Silicon, Homebrew in /opt/homebrew)
          export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"
          
          make

  build-windows:
    runs-on: windows-latest
    continue-on-error: true  # Windows support is experimental, see #183
    permissions:
      contents: read
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_ROOT: C:\vcpkg
    steps:
      - uses: actions/checkout@v6

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: cmake --preset ninja-multi-vcpkg

      - name: Build
        run: cmake --build --preset ninja-multi-vcpkg --config Release
