name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
    steps:
      - uses: actions/checkout@v6
      - name: "Update dependencies"
        run: sudo apt-get update
      - name: "Install dependencies"
        run: sudo apt-get install -y build-essential cmake pkg-config qtbase5-dev libqt5opengl5-dev libgl1-mesa-dev libglu1-mesa-dev libprotobuf-dev protobuf-compiler libode-dev libboost-dev
      - name: "Build"
        run: make

  build-macos:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
    steps:
      - uses: actions/checkout@v6
      - name: "Install dependencies"
        run: brew tap robotology/formulae && brew install cmake pkg-config qt@5 ode
      - name: "Build"
        run: |
          # For macOS 14+  (Apple Silicon, Homebrew in /opt/homebrew)
          export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"
          export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"
          
          make

  build-windows:
    runs-on: windows-latest
    continue-on-error: true  # Windows support is experimental, see #183
    permissions:
      contents: read
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 8eb57355a4ffb410a2e94c07b4dca2dffbee8e50
          vcpkgDirectory: c:/vcpkg  # short path avoids Qt long-path errors

      - name: Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "ninja-multi-vcpkg"
          configurePresetAdditionalArgs: "[-DVCPKG_TARGET_TRIPLET=x64-windows]"
          buildPreset: "ninja-multi-vcpkg"
          buildPresetAdditionalArgs: "['--config Release']"
